### ISSUE TITLE
error Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by suvl** [TheRandomLabs/Scoop-Spotify#58]
While applying a new theme coming from a new, fresh install under Windows 11 and scoop, I had this error:

```
❯ spicetify-apply
spicetify v2.5.0
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc001244000, 0x1bbaf7, 0x1bbaf7, 0xc001244000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc00007c820, 0x42, 0xc0004259d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc00007c820, 0x42, 0xc000580800, 0x25, 0x40, 0xc000042060, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000c6340, 0x35, 0xc000580800, 0x25, 0x40, 0xc000042060, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x12252d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
```

and now spotify looks all black:
![image](https://user-images.githubusercontent.com/6018083/129763009-f66bc3e5-8f23-420b-890f-25891caf8a63.png)

only a purge and a fresh install (without spicetify) does fix spotify after this happens.

**Comment by suvl** [comment]
this is related to https://github.com/khanhas/spicetify-cli/issues/947 and was closed 7 days ago.
